### ISSUE TITLE
[G-COMPASS] Refactoring after moving

### ISSUE THREAD

**Issue by g10z3r** [4rchr4y/go-compass#3]
### Subtasks:
- [x] Convert a field array into a field map in a structure object
- [x] Convert a field array into a field map for an array of generics
- [x] Templating the field structure
- [x] Rename `Analyzer` entity -> `Picker` entity
- [x] Introduce a custom state and encapsulate the file, module name and builders in the state
- [x] Write basic documentation
